In [16]:
import glob
from keras import models
from keras import layers
from keras import optimizers
from keras import activations
from keras import metrics
import numpy as np
import os

In [46]:
# #data preparation
inputDir = "F:\\myProjects\\tim209\\filtered by category\\output\\*.npy"

files = glob.glob( inputDir )
#print( files )

numberOfLabels = len( files ) #each file has a unique label

sources = list()
labelLevelMap = {}
i = 0
for path in files:
    
    label = path.split( "\\" )[-1].replace( ".npy", "" )
    
    sources.append( ( label, path ) )
    
    labelLevelMap[label] = i
    i = i + 1

labels = []
images = []
i = 0
for ( label, path ) in sources:
    
    print( "Processing", label, path )
    
    labelData = np.load( path )
    images.append( labelData )
    
    hotVector = np.array( [0] * numberOfLabels, np.float32 ) #must convert to 32 bit. by default it's 64
    hotVector[i] = 1.0
    i = i + 1
    
    hotVectors = [ hotVector ] * labelData.shape[0] #ndarray for single observations, list for all
    labels.append( hotVectors )
    
images = np.vstack(images)
hotVectors = np.vstack( hotVectors )
    
# inputDir = "F:\\myProjects\\tim209\\filtered by category\\output\\"
# labels = []
# images = []
# for k, npy in enumerate([fn for fn in os.listdir(inputDir) if fn.endswith('.npy')]):
#     d = np.load(os.path.join(inputDir, npy))
#     subset = os.path.splitext(npy)[0]
#     images.append(d)
#     hot_vec = [0]*10
#     hot_vec[k] = 1
#     labels += [hot_vec]*d.shape[0]
# images = np.vstack(images)

    

Processing aircraft carrier F:\myProjects\tim209\filtered by category\output\aircraft carrier.npy
Processing airplane F:\myProjects\tim209\filtered by category\output\airplane.npy
Processing alarm clock F:\myProjects\tim209\filtered by category\output\alarm clock.npy
Processing ambulance F:\myProjects\tim209\filtered by category\output\ambulance.npy
Processing angel F:\myProjects\tim209\filtered by category\output\angel.npy
Processing animal migration F:\myProjects\tim209\filtered by category\output\animal migration.npy
Processing ant F:\myProjects\tim209\filtered by category\output\ant.npy
Processing anvil F:\myProjects\tim209\filtered by category\output\anvil.npy
Processing apple F:\myProjects\tim209\filtered by category\output\apple.npy
Processing arm F:\myProjects\tim209\filtered by category\output\arm.npy


In [45]:

print( labels[0] )
#model 1
model = models.Sequential()

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 

In [25]:
[0] * 10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [28]:
a= [[1, 2, 3 ]] * 3

In [29]:
type( a )

list

In [38]:
a = np.array(range(1,3))

In [40]:
a = a * 10
a

array([10, 20])

In [34]:
a = np.array( labels )

In [35]:
type(a)

numpy.ndarray

In [37]:
a.shape

(100000, 10)

In [47]:
hotVector = np.array( [0.0] * 10 )

In [48]:
hotVector


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
hotVectors = [ hotVector ] * 5

In [54]:

hotVectors = np.vstack( hotVectors )
hotVectors

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
hotVectors.dtype

dtype('float64')