In [84]:
exec(open("initKeras.py").read())

In [72]:
# #data preparation
inputDir = "F:\\myProjects\\tim209\\filtered by category\\output\\*.npy"

files = glob.glob( inputDir )
#print( files )

numberOfLabels = len( files ) #each file has a unique label

sources = list()
labelLevelMap = {}
i = 0
for path in files:
    
    label = path.split( "\\" )[-1].replace( ".npy", "" )
    
    sources.append( ( label, path ) )
    
    labelLevelMap[label] = i
    i = i + 1

labels = []
images = []
i = 0
for ( label, path ) in sources:
    
    print( "Processing", label, path )
    
    labelData = np.load( path )
    images.append( labelData )
    
    hotVector = np.array( [0] * numberOfLabels, np.float32 ) #must convert to 32 bit. by default it's 64
    hotVector[i] = 1.0
    i = i + 1
    
    hotVectors = [ hotVector ] * labelData.shape[0] #ndarray for single observations, list for all
    labels.append( hotVectors )
    
images = np.vstack(images)
labels = np.vstack( labels )
    
# inputDir = "F:\\myProjects\\tim209\\filtered by category\\output\\"
# labels = []
# images = []
# for k, npy in enumerate([fn for fn in os.listdir(inputDir) if fn.endswith('.npy')]):
#     d = np.load(os.path.join(inputDir, npy))
#     subset = os.path.splitext(npy)[0]
#     images.append(d)
#     hot_vec = [0]*10
#     hot_vec[k] = 1
#     labels += [hot_vec]*d.shape[0]
# images = np.vstack(images)

    

Processing aircraft carrier F:\myProjects\tim209\filtered by category\output\aircraft carrier.npy
Processing airplane F:\myProjects\tim209\filtered by category\output\airplane.npy
Processing alarm clock F:\myProjects\tim209\filtered by category\output\alarm clock.npy
Processing ambulance F:\myProjects\tim209\filtered by category\output\ambulance.npy
Processing angel F:\myProjects\tim209\filtered by category\output\angel.npy
Processing animal migration F:\myProjects\tim209\filtered by category\output\animal migration.npy
Processing ant F:\myProjects\tim209\filtered by category\output\ant.npy
Processing anvil F:\myProjects\tim209\filtered by category\output\anvil.npy
Processing apple F:\myProjects\tim209\filtered by category\output\apple.npy
Processing arm F:\myProjects\tim209\filtered by category\output\arm.npy


In [58]:

print( labels[0] )
print( labels[10000] )
print( labels[30000] )
#model 1
model = models.Sequential()

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
